### ISSUE TITLE
README should state the supported versions

### ISSUE THREAD

**Issue by janv8000** [ParticularLabs/RavenToSqlPersistence#4]
As part of a migration from NSB4 (with RavenDB persistence) to NSB<latest> (with SQL persistence) I was evaluating this tool to see if it was possible to do a zero downtime migration.

NSB6 uses the SubscriptionV2 format however.
I tried adding the SubscriptionV1toV2Converter listener to the documentstore. This helped migrate the LegacyAddresses.

With the changes introduced in the following issues https://github.com/Particular/NServiceBus.RavenDB/issues/280, https://github.com/Particular/NServiceBus.RavenDB/issues/281, https://github.com/Particular/NServiceBus.RavenDB/issues/284 the `EndPoint` property is empty and the following code fails:

```
var newSubscriber = new Subscriber(client.TransportAddress, client.Endpoint);
```

=> it would be nice if README could state that only V6+ is supported

**Comment by DavidBoike** [comment]
Hi @janv8000,

Because SQL Persistence requires NServiceBus 6 I was assuming (you know what they say about assuming) that the requirement for V6 was obvious. Sorry! I've updated the README to be more explicit.

Thanks!
