### ISSUE TITLE
TimeoutConverter only converts the first 1024 timeouts

### ISSUE THREAD

**Issue by rune-berge** [ParticularLabs/RavenToSqlPersistence#5]
The SagaConverter class uses paging, but the TimeoutConverter just loads the first 1024 documents.

https://github.com/ParticularLabs/RavenToSqlPersistence/blob/0222d00f3ad0d9c9f40cdd1ebd3e80dfd3881a2f/RavenToSqlPersistence/Timeouts/TimeoutConverter.cs#L12

Is there a reason the RavenEnumerator class is not used for timeouts?

**Comment by DavidBoike** [comment]
@rune-berge probably just an oversight.

@mauroservienti can you take a look?

**Comment by rune-berge** [comment]
I changed it to use docStore.AllDocumentsStartingWith like the SagaConverter in our local fork and it worked fine

**Comment by mauroservienti** [comment]
@rune-berge thanks for raising this. I raised https://github.com/ParticularLabs/RavenToSqlPersistence/pull/6 to fix this.
